### ISSUE TITLE
accepted at a conference?

### ISSUE THREAD

**Issue by jS5t3r** [Daizy97/SaliencyAttack#3]
Hello, 

is the Saliency Attack accepted at any conference or workshop? 

https://arxiv.org/abs/2206.01898

best, Peter

**Comment by Daizy97** [comment]
Hi,

Our work _**Saliency Attack: Towards Imperceptible Black-box Adversarial Attack**_ has been just accepted by ACM Transactions on Intelligent Systems and Technology: https://dl.acm.org/doi/10.1145/3582563

Thanks for your attention.
