### ISSUE TITLE
disabled  site of database

### ISSUE THREAD

**Issue by pdsu-zjl** [Daizy97/SaliencyAttack#4]
Hello，recently，i am learning  code of saliency attacks ，and now  i find that  your site of database is deisabled.  So，i entreate you can sent a new site about the first database，please.   Thanks

**Comment by Daizy97** [comment]
Hi,

You can manually download the datasets from the website [ILSVRC2012](https://image-net.org/challenges/LSVRC/2012/2012-downloads.php), or use the command:
`wget https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_val.tar`

Thanks

**Comment by pdsu-zjl** [comment]
> Hi,
> 
> You can manually download the datasets from the website [ILSVRC2012](https://image-net.org/challenges/LSVRC/2012/2012-downloads.php), or use the command: `wget https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_val.tar`
> 
> Thanks
  Sincerely thank you

  Are you aware of some attack algorithms on semantic segmentation of images that can interfere with the neural network model to generate accurate GT ? If you know something about it ,please recommend some papers and codes to me.

Best wishes to you

**Comment by pdsu-zjl** [comment]
I sincerely thank you for your answer. After reading your article, I think you must have deep attainments in network attack. So  I want to ask you one more question . Are you aware of some attack algorithms on semantic segmentation of images that can interfere with the  neural network model to generate accurate GT ? If you know something about it ,please recommend some papers and codes to me.


Thank you again


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Daizy97/SaliencyAttack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Daizy97/SaliencyAttack] disabled  site of database (Issue #4)





 
Hi,
 
You can manually download the datasets from the website ILSVRC2012, or use the command:
 wget https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_val.tar
 
Thanks

**Comment by Daizy97** [comment]
Hi,

I'm sorry that currently I just focus on adversarial attack on image classification task. For attack on semantic segmentation task, you can search for related papers with some key words from google scholar, and then extend to more papers.

Good luck

**Comment by pdsu-zjl** [comment]
All right. Thank you for your advices.


May you have more scientific research achievements in the future.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月31日(星期五) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Daizy97/SaliencyAttack] disabled  site of database (Issue #4)





 
Hi,
 
I'm sorry that currently I just focus on adversarial attack on image classification task. For attack on semantic segmentation task, you can search for related papers with some key words from google scholar, and then extend to more papers.
 
Good luck
